delete_event_by_uid:
  target:
    entity:
      domain: calendar
      supported_features:
        - calendar.CalendarEntityFeature.DELETE_EVENT
  fields:
    uid:
      required: true
      example: "2de6ebdc-d231-11f0-b737-497e7c4deb61"
      selector:
        text:
    recurrence_id:
      example: "20251206T144500Z"
      selector:
        text:
    recurrence_range:
      example: "20251206T144500Z/20251231T150000Z"
      selector:
        text:
update_event_by_uid:
  target:
    entity:
      domain: calendar
      supported_features:
        - calendar.CalendarEntityFeature.UPDATE_EVENT
  fields:
    uid:
      required: true
      example: "2de6ebdc-d231-11f0-b737-497e7c4deb61"
      selector:
        text:
    summary:
      example: "Department Party"
      selector:
        text:
    description:
      example: "Meeting to provide technical review for 'Phoenix' design."
      selector:
        text:
    start_date_time:
      example: "2022-03-22 20:00:00"
      selector:
        datetime:
    end_date_time:
      example: "2022-03-22 22:00:00"
      selector:
        datetime:
    start_date:
      example: "2022-03-22"
      selector:
        date:
    end_date:
      example: "2022-03-23"
      selector:
        date:
    in:
      example: '{"days": 2} or {"weeks": 2}'
    location:
      example: "Conference Room - F123, Bldg. 002"
      selector:
        text:
get_events:
  target:
    entity:
      domain: calendar
  fields:
    start_date_time:
      example: "2022-03-22 20:00:00"
      selector:
        datetime:
    end_date_time:
      example: "2022-03-22 22:00:00"
      selector:
        datetime:
    duration:
      selector:
        duration:
